name: Discord notification
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  notify-discord-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.WEBHOOK_LINK }}
          message: "Updated changelog\nDiff: {{ github.context.payload.compare }}"
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
