name: Discord notification
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  notify-discord-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ secrets.WEBHOOK_LINK }}
          message: '**{{ commit.title }}**\n{{ commit.description }}'
          embed: '{"components":[{"type":1,"components":[{"style":5,"label":"View changes","url":"{{ github.context.payload.compare }}","disabled":false,"type":2}]}]}'