name: Discord notification

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  notify-discord-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: discord-webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          # Discord webhook URL
          webhook_url: ${{ secrets.WEBHOOK_LINK }}
          # Hide the full GitHub username
          censor_username: true
          # Color of the Discord embed
          color: '#f0771a'
